/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "bazaarapi",
            "endpoint": "https://meb0drrbyj.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:574dfb0c-b1db-4a09-8d39-427a5d396ff8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_weEwQmOIZ",
    "aws_user_pools_web_client_id": "658ehl0khi75tg1h2dsteq9pbm",
    "oauth": {},
    "aws_user_files_s3_bucket": "bazaarbucket113324-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
